INSERT INTO "food" ("name", "serving_size_gram", "source", "image_url") VALUES
                                                                            ('Pizza', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg'),
                                                                            ('Hamburger', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Hamburger_%28black_bg%29.jpg'),
                                                                            ('French Fries', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/French_Fries.JPG'),
                                                                            ('Fried Chicken', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Fried-Chicken-Set.jpg'),
                                                                            ('Spaghetti Bolognese', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/5/55/Spaghetti_alla_Bolognese.jpg'),
                                                                            ('Hot Dog', 180, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Hot_dog_with_mustard.png'),
                                                                            ('Sushi', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg'),
                                                                            ('Tacos', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Plate_of_tacos.jpg'),
                                                                            ('Ramen', 400, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Tonkotsu_Ramen.jpg'),
                                                                            ('Steak', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Steak_03_bg_040306.jpg'),
                                                                            ('Pasta Carbonara', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Spaghetti_alla_Carbonara_%28cropped%29.jpg'),
                                                                            ('Ice Cream', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Ice_Cream_dessert_02.jpg'),
                                                                            ('Chocolate Cake', 120, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Chocolate_cake_with_chocolate_frosting.jpg'),
                                                                            ('Cheeseburger', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/RedDot_Burger.jpg'),
                                                                            ('Lasagna', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Lasagna_%281%29.jpg'),
                                                                            ('Donuts', 80, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Glazed-Donut.jpg'),
                                                                            ('Croissant', 60, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Croissant-Petr-Kratochvil.jpg'),
                                                                            ('Pancakes', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Blueberry_pancakes_%282%29.jpg'),
                                                                            ('Chicken Nuggets', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Chicken_Nuggets.jpg'),
                                                                            ('Mac and Cheese', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Macaroni_and_cheese.jpg'),
                                                                            ('Fried Rice', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Chicken_fried_rice.jpg'),
                                                                            ('Curry (Chicken)', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Chicken_Tikka_Masala.jpg'),
                                                                            ('Pho', 350, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Pho-Vietnamese-noodle-soup-01.jpg'),
                                                                            ('Spring Rolls', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Vietnamese_spring_rolls.jpg'),
                                                                            ('Nasi Goreng', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Nasi_Goreng_Indonesian_Fried_Rice.jpg');


INSERT INTO "food" ("name", "serving_size_gram", "source", "image_url") VALUES
                                                                            ('Falafel', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Falafel_with_hummus_and_tabouli.jpg'),
                                                                            ('Hummus', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Hummus_with_pine_nuts_and_olive_oil.jpg'),
                                                                            ('Shawarma', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Shawarma_vegetables.jpg'),
                                                                            ('Gyros', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Gyros_Plate.jpg'),
                                                                            ('Kebab', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Kebab_Kazan.jpg'),
                                                                            ('Paella', 350, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Paella_mixta.jpg'),
                                                                            ('Dim Sum', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Dim_Sum_HK.jpg'),
                                                                            ('Peking Duck', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Peking_Duck_-_served_with_pancakes%2C_scallions_and_hoisin_sauce.jpg'),
                                                                            ('Kimchi', 50, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Kimchi_on_dish.jpg'),
                                                                            ('Bibimbap', 350, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Dolsot-bibimbap.jpg'),
                                                                            ('Bulgogi', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/62/Bulgogi_2.jpg'),
                                                                            ('Tempura', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Shrimp_tempura.jpg'),
                                                                            ('Gyoza', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Gyoza20051222.jpg'),
                                                                            ('Miso Soup', 200, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Miso_Soup_in_Nagoya.jpg'),
                                                                            ('Ceviche', 180, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Ceviche_Peruano.jpg'),
                                                                            ('Tiramisu', 120, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Tiramisu_-_Ristorante_Croce_Bianca_-_Tirano_-_Italy.jpg'),
                                                                            ('Crepes', 150, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Crepes_with_berries.jpg'),
                                                                            ('Churros', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Churros.jpg'),
                                                                            ('Poutine', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Poutine_Burger_Bar_Crescent.jpg'),
                                                                            ('Baklava', 80, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Baklava_-_Turkish_special%2C_80_pieces.jpg'),
                                                                            ('Samosa', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Samosa_dish.jpg'),
                                                                            ('Onigiri', 100, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Onigiri_with_Ume.jpg'),
                                                                            ('Fajitas', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Chicken_fajitas.jpg'),
                                                                            ('Enchiladas', 300, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Enchiladas_with_mole.jpg'),
                                                                            ('Quiche', 250, 'GlobalDB', 'https://upload.wikimedia.org/wikipedia/commons/0/02/Quiche_with_spinach.jpg');

INSERT INTO "food" ("name", "serving_size_gram", "source", "image_url") VALUES
                                                                            ('Beef Steak', 250, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/4/44/Beef_steak_rare.jpg'),
                                                                            ('Grilled Chicken Breast', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Grilled_Chicken_Breast.jpg'),
                                                                            ('Lamb Chops', 220, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Lamb_Chops.jpg'),
                                                                            ('Pork Ribs', 300, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/d/db/Barbecue_pork_ribs.jpg'),
                                                                            ('Roast Duck', 280, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/3/37/Roast_Duck.jpg'),
                                                                            ('Wiener Schnitzel', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Wiener_Schnitzel.jpg'),
                                                                            ('Chicken Tikka', 180, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Chicken_Tikka.jpg'),
                                                                            ('Teriyaki Chicken', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Teriyaki_chicken.jpg'),
                                                                            ('Barbecue Brisket', 280, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/0/06/BBQ_Brisket.jpg'),
                                                                            ('Braised Short Ribs', 300, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Braised_short_ribs.jpg'),
                                                                            ('Korean Bulgogi Beef', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/6/62/Bulgogi_2.jpg'),
                                                                            ('Jamaican Jerk Chicken', 220, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Jerk_Chicken_Jamaica.jpg'),
                                                                            ('Peking Duck', 250, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Peking_Duck_-_served_with_pancakes%2C_scallions_and_hoisin_sauce.jpg'),
                                                                            ('Grilled Salmon', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Grilled_Salmon_Steak.jpg'),
                                                                            ('Côte de Boeuf', 350, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Cote_de_boeuf.jpg'),
                                                                            ('Chicken Kiev', 220, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Chicken_Kiev.jpg'),
                                                                            ('Duck à l’Orange', 300, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Duck_a_l%27orange.jpg'),
                                                                            ('Osso Buco', 320, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Osso_Buco.jpg'),
                                                                            ('Salisbury Steak', 250, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Salisbury_steak.jpg'),
                                                                            ('Filet Mignon', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Filet_mignon.jpg'),
                                                                            ('Turkey Roast', 280, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Roast_turkey.jpg'),
                                                                            ('Chili Con Carne', 300, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Chili_con_carne.jpg'),
                                                                            ('Coq au Vin', 300, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Coq_au_vin_with_risotto.jpg'),
                                                                            ('Pork Schnitzel', 200, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Pork_Schnitzel.jpg'),
                                                                            ('Venison Steak', 250, 'Wikipedia', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Venison_Steak.jpg');

INSERT INTO "food" ("name", "serving_size_gram", "source", "image_url") VALUES
                                                                            ('Phở', 350, 'Vietnamese Food Composition Table', 'https://media-cdn-v2.laodong.vn/storage/newsportal/2024/9/27/1400438/Pho-4.jpg'),
                                                                            ('Cơm trắng', 100, 'Vietnamese Food Composition Table', 'https://cdn.tgdd.vn/2021/07/CookProduct/2-1200x676-2-1200x676-3.jpg'),
                                                                            ('Trứng', 50, 'USDA', 'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2025/3/8/photo-1741408427825-17414084285131651116857.jpeg'),
                                                                            ('Bánh mì', 60, 'Vietnamese Food Composition Table', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUduatDvdNjbF1e_37OBHe2RfHnimO_MiaPg&s'),
                                                                            ('Bơ (Butter)', 14, 'USDA', 'https://cdn.britannica.com/27/122027-050-EAA86783/Butter.jpg');
