services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      # lưu data
      - db_data:/var/lib/postgresql/data

      # init SQL (Run the first time only)
      - ./database/sql-compose:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: go_backend
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  db_data: